- server/src/auth/calling-user.decorator.ts
The calling-user decorator is used to get a user from a socket.io call. It had a small error that needed to be fixed
Not applicable
> Fixed an issue with the calling-user decorator [very small]

- server/src/group/group.gateway.ts
- server/src/group/group.service.ts
This pull request is the first step towards implementing feature Group.Gateway
- build the structure of requestGroupData(how gateway.ts access service.ts)
-  learn about database and finish requestGroupData's database manipulation part
Test with postman.
Need some research about ws testing
> GroupGateway

- README.md
Depends on #{number of PR}
- A newly discovered dependency that hasn’t been addressed
- Database schema change (anything that changes TypeORM entities)
- Other change that could cause problems (Detailed in notes)
> added names to the readMe contributer list

- admin/package.json
- admin/src/DataTable.tsx
]
Create sample data that has click functions, see if it works
> Add support for clickFunc and a support for editable props

- package.json
- server/src/group/group.gateway.ts
- server/src/group/group.module.ts
- server/src/group/group.service.ts
This pull request implements part of GroupGateway.
> Added requestGroupData in GroupGateway and getGroupForUser in GroupService

- README.md
This pull request adds Chris to the readme
> Added Chris to readme

- README.md
- game/ios/GoogleService-Info.plist
- game/ios/Podfile.lock
- game/ios/Runner.xcodeproj/project.pbxproj
- game/lib/api/game_api.dart
- game/lib/api/game_client_api.dart
- game/lib/api/game_client_dto.dart
- game/lib/api/game_server_api.dart
- game/lib/main.dart
- game/lib/model/challenge_model.dart
- game/lib/model/event_model.dart
- game/lib/model/group_model.dart
- game/lib/model/reward_model.dart
- game/lib/model/tracker_model.dart
- game/lib/model/user_model.dart
- server/src/client/update-event-data.dto.ts
- server/src/event/event.gateway.ts
- server/src/event/request-event-data.dto.ts
This pull request is the first step towards implementing state management for flutter.
Test if the model works.
> Added state management for flutter app.

- README.md
Depends on #{number of PR}
- A newly discovered dependency that hasn’t been addressed
- Database schema change (anything that changes TypeORM entities)
- Other change that could cause problems (Detailed in notes)
> Added Brian to ReadMe

- admin/src/components/Challenges.tsx
- admin/src/components/Events.tsx
- admin/src/components/Rewards.tsx
- server/src/challenge/challenge.gateway.ts
- server/src/challenge/challenge.service.ts
- server/src/user/user.service.ts
> Added ids to the frontend

- README.md
- game/lib/events/events_widget.dart
- game/lib/home_page/home_page_widget.dart
- game/lib/leaderboard/leaderboard_widget.dart
- game/lib/main.dart
- game/lib/model/event_model.dart
- game/lib/widget/leaderboard_cell.dart
- game/lib/widget/leaderboard_user_cell.dart
- server/src/challenge/challenge.gateway.ts
- server/src/event/event.service.ts
- server/src/group/group.module.ts
- server/src/user/user.gateway.ts
Fixed minor dart define issue and some basic backend bugs.
> Fixed dart define issue.

- server/src/app.module.ts
- server/src/group/group.service.ts
Fixed crash and data corruption related to the host leaving a group.
> Fixed leaving logic.

- admin/src/components/Events.tsx
- admin/src/components/ServerApi.tsx
- admin/src/components/ServerData.tsx
- admin/src/dto/request-restrictions.dto.ts
- admin/src/dto/update-restrictions.dto.ts
- server/mikro-orm.config.ts
- server/package.json
- server/src/admin/admin-callback/admin-callback.service.ts
- server/src/admin/admin.gateway.ts
- server/src/admin/admin.module.ts
- server/src/admin/admin.service.ts
- server/src/admin/request-restrictions.dto.ts
- server/src/admin/update-restrictions.dto.ts
- server/src/event/event.gateway.ts
- server/src/event/event.service.ts
- server/src/group/group.service.ts
- server/src/migrations/.snapshot-postgres.json
- server/src/migrations/Migration20220426163141.ts
- server/src/model/event-base.entity.ts
- server/src/model/event-reward.entity.ts
- server/src/model/group.entity.ts
- server/src/model/restriction-group.entity.ts
- server/src/model/user.entity.ts
- server/src/user/user.gateway.ts
- server/src/user/user.service.ts
This pull request is the first step toward implementing restrictions on users.
Use Postman to test the API + implement frontend and test
> Added restrictions.

- game/lib/events/event_cell.dart
- game/lib/events/events_widget.dart
- game/lib/rewarded/rewarded_page.dart
- server/src/group/group.service.ts
Cleaned up some areas of code in the server and flutter app.
- Some comments added to difficult areas in the server code.
- Indentation altered on large flutter code blocks to help with readability.
None needed since all significant changes are only semantics.
> Cleaned up some areas of code in the server and flutter app

- admin/tsconfig.json
- game/lib/login/login_page.dart
- game/lib/widget/leaderboard_user_cell.dart
- game/lib/widget/nav_bar.dart
- game/lib/widget/nav_widget.dart
- game/lib/widget/rewards_cell.dart
- game/lib/widget/visited_places_cell.dart
- Removed duplicate/unused imports
- Used Carnelian in nav_bar like in other dart files
> Clean code brian

- game/lib/rewarded/rewarded_page.dart
- game/lib/rewards/rewards_widget.dart
- game/lib/settings/settings.dart
- game/lib/suggestions/suggestions.dart
- game/lib/username/username_widget.dart
- game/lib/utils/utility_functions.dart
- game/lib/visited_places/visited_places_widget.dart
Cleaned up some indentation in the flutter app for readability.
> Flutter Clean Code

- admin/package.json
- admin/src/App.tsx
- admin/src/components/Groups.tsx
- admin/src/components/ServerApi.tsx
- admin/src/components/ServerData.tsx
- admin/src/decs.d.ts
- admin/src/dto/request-groups.dto.ts
- admin/src/dto/update-group-data.dto.ts
- admin/src/dto/update-groups.dto.ts
- server/src/admin/admin-callback/admin-callback.service.ts
- server/src/admin/admin-callback/update-group-data.dto.ts
- server/src/admin/admin.gateway.ts
- server/src/admin/admin.module.ts
- server/src/admin/admin.service.ts
- server/src/admin/request-groups.dto.ts
- server/src/admin/update-groups.dto.ts
This pull request is the first step to allowing groups to be seen and broken apart. 
> Admin frontpage group management

- admin/src/components/ServerApi.tsx
- admin/src/components/ServerData.tsx
This pull request is the first step towards implementing documentation
> Frontend Documentation

- server/prisma/migrations/20221129233927_reward_order/migration.sql
- server/prisma/schema.prisma
- server/src/admin/admin.service.ts
Fix event deletion on admin frontend
Fix challenge deletion on admin frontend
Fix changing reward priorities on admin frontend by adding reward indices
Further QA testing
> Miscellaneous QA Bug Fixes For Frontend

- game/android/app/build.gradle
- game/android/build.gradle
- game/android/gradle/wrapper/gradle-wrapper.properties
Fix flutter not running updating gradle version to the latest
Someone please pull and try on their own computer
> update Kotlin and gradle versions

- server/.env
> fixed scripts to simplify db work

- admin/src/components/Rewards.tsx
- admin/src/dto/reward.dto.ts
- scripts/dbreset.js
- server/prisma/schema.prisma
- server/src/reward/reward.dto.ts
- server/src/reward/reward.gateway.ts
- server/src/reward/reward.service.ts
Add isAchievement and points to reward field
Need to test in postman
- Database schema change (anything that changes TypeORM entities)
> add isAchievement and points as a field to reward

- admin/src/dto/user.dto.ts
- game/lib/api/game_client_dto.dart
- game/lib/api/game_server_api.dart
- server/prisma/schema.prisma
- server/src/auth/apple/apple.controller.ts
- server/src/auth/auth.service.ts
- server/src/auth/device-login/device-login.controller.ts
- server/src/auth/google/google.controller.ts
- server/src/auth/login.dto.ts
- server/src/user/majors.txt
- server/src/user/user.dto.ts
- server/src/user/user.gateway.ts
- server/src/user/user.service.ts
The registration flow in the new app requires information about the user’s username, major, and year. The rest API route and database must be modified to include this new concept.
Standard Postman testing
- Database schema change
> Changing Registration Flow to add Username, Major, and Graduation Year

- game/ios/Flutter/AppFrameworkInfo.plist
- game/ios/Podfile.lock
- game/ios/Runner.xcodeproj/project.pbxproj
- game/ios/Runner/Info.plist
- game/lib/api/game_api.dart
- game/lib/api/game_client_api.dart
- game/lib/api/game_client_dto.dart
- game/lib/model/user_model.dart
- game/lib/username/username_widget.dart
- game/pubspec.yaml
In this PR, I updated versions and deployment targets for the Flutter app to run on iOS simulators.
Also fixed a bug that requests location when another request is already running, causing the app to crash.
Note: 
App currently configured to run on iOS 15.2
Current version of Flutter: 3.3.x
> Made changes to Flutter packages and deployment versions.

- server/src/challenge/challenge.gateway.ts
- server/src/challenge/challenge.service.ts
- server/src/client/client.service.ts
- server/src/event/event.gateway.ts
- server/src/group/group.gateway.ts
- server/src/organization/organization.gateway.ts
- server/src/reward/reward.gateway.ts
- server/src/user/user.service.ts
Need to test errors on frontend
> create error function and errors propagation for challenges

- game/lib/challenges/challenge_cell_new.dart
- game/lib/challenges/challenges_page.dart
- game/lib/journeys/journey_cell.dart
- game/lib/main.dart
This pull request is the first step the challenge page
test in frontend
> Challenges page

- game/lib/api/game_client_dto.dart
- game/lib/challenges/challenge_cell.dart
- game/lib/challenges/challenges_widget.dart
- game/lib/model/challenge_model.dart
- game/lib/model/event_model.dart
In this PR, I fixed the Challenge DTO and Challenge Model on the Flutter app to be in line with the new DTO on the backend.
Also added a placeholder widget for the ChallengeCell so that there are no compile time issues.
> Fix challenge dto, add placeholder challenge cell widget.

- scripts/setup.js
Changed npm run tests -- e2e to npm run tests:e2e
> Fix setup tests typo.

- server/src/challenge/challenge.e2e-spec.ts
This pull request is the first step towards implementing challenges e2e tests
> E2E tests for challenge module

- README.md
Updated README to add contributors for FA23.
> updated contributors for fa23

- game/lib/profile_page/achievement_cell.dart
- game/lib/profile_page/completed_cell.dart
- game/lib/profile_page/profile_page_widget.dart
This pull request is the first step towards implementing feature a new profile design
- created achievement cell widget and implemented styles and formatting
- created completed cell widget and implemented styles and formatting
- build out profile page and bring in other widgets
- work on the personal header at the top
- Bring in real data
> Profile page redesign

- README.md
Updated ReadMe to include sp24 contributors. 
This pull request is the first step towards finishing onboarding onto Cornell Go
> added sp24 contributers to readme

- .gitattributes
Change CRLF to LF line endings
> Change CRLF to LF line endings

- README.md
Adding New Member Names (Temi and Joshua) to readme. This is a test pull request for me to get familiar with the git operations.
> New member readme update 

- server/src/user/user.service.ts
Addresses [github.com/cornell-dti/cornell-go/security/code-scanning/1](http://github.com/cornell-dti/cornell-go/security/code-scanning/1)
> Fix overly permissive regex range security issue

- server/src/casl/casl-ability.factory.ts
- server/src/organization/organization.e2e-spec.ts
- server/src/user/user.gateway.ts
Users can now see all challenges but not necessarily lat or long. Joining an org should allow you to see achievements of that org too.
> Fix challenge + join org issue

- game/lib/journeys/journeys_page.dart
This pull request is to fix the Journeys search bar bug, where no results would show for any searches other than "e".
> Fix Journeys Search Bar Bug

- game/ios/Podfile
- game/ios/Podfile.lock
- game/ios/Runner.xcodeproj/project.pbxproj
- game/lib/main.dart
- game/pubspec.lock
- game/pubspec.yaml
This pull request is to try fixing the Testflight Issue we are having, where there is an error authenticating users/signing new users up. I updated main.dart so that it uses Flutter Config Plus instead of Flutter Config and fixed other issues that were causing errors in simulation. We still need to test these changes in Testflight to see if that fixes the issue we're facing.
If we are still having issues with signing in, we may need to pause and revert to an older version of the app and build from there for the sake of soft launch.
> Fixing Potential Dependency Issues
